version: '3.8'

services:
  geth:
    image: ethereum/client-go
    ports:
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 30303:30303
      - 30304:30304
    volumes:
      - ./config/genesis.json:/genesis.json
      - ./scripts/start.sh:/start.sh
      - ./keystore:/${DATADIR}/keystore
    environment:
      DATADIR: ${DATADIR}
      COINBASE_PASS: ${COINBASE_PASS}
    entrypoint: /start.sh
