version: '3.9'

services:
  chain1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8545:8545
      - 8546:8546
      - 8547:8547
    volumes:
      - ./config/genesis.json:/genesis.json
      - ./scripts/mounted/start.sh:/start.sh
      - ./keystore:${DATADIR}/keystore
    environment:
      CHAIN_ID: 8545
      DATADIR: ${DATADIR}
      COINBASE_PASS: ${COINBASE_PASS}
    entrypoint: /start.sh

  chain2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 9545:8545
      - 9546:8546
      - 9547:8547
    volumes:
      - ./config/genesis.json:/genesis.json
      - ./scripts/mounted/start.sh:/start.sh
      - ./keystore:${DATADIR}/keystore
    environment:
      CHAIN_ID: 9545
      DATADIR: ${DATADIR}
      COINBASE_PASS: ${COINBASE_PASS}
    entrypoint: /start.sh
